### ISSUE TITLE
Can't find the place where embedding pickle file is created

### ISSUE THREAD

**Issue by wolterlw** [entron/entity-embedding-rossmann#13]
I'm sorry for such a question, but I can not figure out how you pretrained the embeddings.
I was looking for a function that writes to the embeddings pickle file but found none.
Also I could not understand from the paper whether you trained the embeddings on auxiliary tasks or they where formed in the process of optimizing for the main objective.

**Comment by entron** [comment]
It is in the script but not inside a function. The embeddings are trained in the process of optimizing for the main objective.
