### ISSUE TITLE
The embedding layer

### ISSUE THREAD

**Issue by germayneng** [entron/entity-embedding-rossmann#14]
Hi Entron, 

Noticed you also updated your code to keras 2.0! This is really helpful s

May i ask a simple question? For each embedding input you define, how do we visualize the embedding layer? (pardon my silliness ) 

For example lets suppose we have only this 2 for the embedding layer 

![image](https://user-images.githubusercontent.com/22788747/42253846-4ab86b3e-7f76-11e8-8356-390c89ef2021.png)

```
output_embeddings = [output_dow, output_promo,]

output_model = Concatenate()(output_embeddings)
```

the output promo defined 1 hidden layer while we have the embedding layer. Therefore, how many units are there in this particular layer? 

Are there a total of 1 + 6? or each embedding count as 1 so 1 + 1 = 2 units in this layer

**Comment by entron** [comment]
Hi germayneng, 

For promo there is just one simple neuron with one input and one output. The input is either 0 or 1 if I remember correctly and the output will be two real numbers. So you can say it embeds two integers into a 1D real space.

For DOW it embeds 7 days into a 6D space. 

Hope I have answered your question.

**Comment by germayneng** [comment]
I think the new functional api is easier to understood. May i also throw u another? For the 'old version',
you build various sequential() models which you merge after. For the embedding function, you used to have this arg called input length. This is not needed due to the functional api which is easier to grasp.

for input length, which you used to define, is the input length the number of columns of the input?

**Comment by germayneng** [comment]
Sorry entron, one last question: 

i am confused over the input_shape you used. isnt input shape = (1, ) meant that the number of samples if the input? why is it 1 in this case? shouldn't it be the number of rows?
