### ISSUE TITLE
Connecting embedding weights to a categorical value

### ISSUE THREAD

**Issue by gilad19** [entron/entity-embedding-rossmann#16]
Hi Entron, 

Thanks for sharing your code here! 

I have data with 100,000 rows, a single categorical feature with 300 distinct values and additional continues variables. I am merging the categorical feature after label encoding with the continuous ones and running training for a classification problem with NN successfully. 

I am using the following code for the embedding of the categorical feature to 5 dimensions:
input_leaf = Input(shape=(1,))
output_leaf = Embedding(300, 5, name='category_embed')(input_leaf)

Next, I am trying to extract the information from the embedding layer in order to use it in XGBoost as new features. However, the output of the following code:
model.get_layer('category_embed').get_weights()[0]
is a weights matrix in the shape of 300x5. My trouble is that I don't know how to map those weights to the original categorical values (e.g. 22 = [0.2, -0.1, 0.6, 2, 3]). 

Any help will be highly appreciated! 
Gilad

**Comment by entron** [comment]
Hi Gilad,

Maybe the embed_features function in the file https://github.com/entron/entity-embedding-rossmann/blob/master/models.py is what you want?
