### ISSUE TITLE
Categorizations choice

### ISSUE THREAD

**Issue by prekratko** [entron/entity-embedding-rossmann#17]
Hi entron.
This is more like conceptual question.
I'm reading your source and docs and I can see that you have categorized many features alone by themselves but you haven't, for example, combined several of them into single embedding.
By this I mean to use very similar features by nature in an embedding group whose resulting vector would represent "behaviour" of the group, maybe better than each feature solo categorized.
Did you try something like that? If yes, can you share your conclusions?
Thank you.

**Comment by entron** [comment]
Hi prekratko,

Sorry for the late response. This is a very good question. Indeed I have tried the idea you have while joining the competition. I called it tree embeddings. The results were not as good as without using tree embeddings. However, I only had very limited time to try this idea so I think it worth further exploration.

**Comment by prekratko** [comment]
Hi.
Thank you.
So, this is open topic for more R&D.
