### ISSUE TITLE
Why not all features are used

### ISSUE THREAD

**Issue by claudehang** [entron/entity-embedding-rossmann#22]
Hi,
Thanks for your code. I notice that the features for training are as:
```
return [store_open,
            store_index,
            day_of_week,
            promo,
            year,
            month,
            day,
            store_data[store_index - 1]['State']
            ]
```
but there are lots of other features like in `store.csv`:
```
Assortment | CompetitionDistance | CompetitionOpenSinceMonth | CompetitionOpenSinceYear
```
Could you share the consideration why you not using these as features? Thx!

**Comment by entron** [comment]
Sorry for the late response. The master branch is a simplified version used by the paper. All features are used in the kaggle branch: https://github.com/entron/entity-embedding-rossmann/tree/kaggle
