### ISSUE TITLE
How to build store_states.csv

### ISSUE THREAD

**Issue by caomaocao** [entron/entity-embedding-rossmann#4]
Hi:
   I noticed that store_states.csv in the repo.  It describes where the store is . This csv is not belongs to Kaggle. So, how to build it?  Thank you.

**Comment by entron** [comment]
It was created by the Kaggler dune_dweller. You can find it here: [Putting stores on the map](https://www.kaggle.com/c/rossmann-store-sales/forums/t/17048/putting-stores-on-the-map)
