### ISSUE TITLE
CAN NOT FIND "embeddings.pickle" anywhere

### ISSUE THREAD

**Issue by notingbad** [entron/entity-embedding-rossmann#5]
Hi,
  I'm trying to learn your paper but something wrong with my code. I try to locate the error and I found the file named "embeddings.pickle" was everywhere but I just cannot find how to create it. I noticed the comment "# Use plot_embeddings.ipynb to create" but still I cannot find out the answer.
 I'm wondering if you can give me a hand, thanks a lot.

**Comment by entron** [comment]
In the file train_test_model.py you can find the code to save the embeddings under the line: 
```
if save_embeddings:
```

**Comment by notingbad** [comment]
Thank you very much!
