### ISSUE TITLE
when do u decide to dense or embed?

### ISSUE THREAD

**Issue by germayneng** [entron/entity-embedding-rossmann#7]
Hi entron, 

really very awesome and learnt alot from your work. However, i do have a question and i think this is the most appropriate place to ask. 

Looking at your script, what is the methodology to decide to embed a variable or dense a variable. For example u chose to make variable like promo as a dense layer ...etc . Is there a reason for those that were chosen as a dense layer?

**Comment by entron** [comment]
Hi germayneng, 

glad you find it helpful. Entity embedding is especially useful for large categorical variables like the store id. The promo variable as far as I remember is binary so there is no need to use entity embedding.

**Comment by germayneng** [comment]
so basically for variables that are binary, or discrete we can pass them using a dense layer which in your case, promo. I believe there are a couple which you pass as dense layer. 

One more question: Does the order matters? or can i pass all the large categorical variables (embedding layers) and then pass the dense layers at the end

**Comment by entron** [comment]
Discrete variables are categorical, and you should consider using entity embedding if it is large. The order doesn't matter.

**Comment by germayneng** [comment]
I implemented it recently in a kaggle competition. What i did was to train the NN model and extract the weights depending on the order in the layer. For example, If a variable holds unique values such as [-1,0,1] (let us take 3 values for example), the embedding will return a vector that represents the unique values. Next, I merge the embedding to replace the 3 values. so again ,example 

- 1 ===== [0,1,2]
0 ===== [23,43,12]
1 ===== [23,21,12] 
where the vectors are the from the NN weights. Is this correct based on my understanding?

**Comment by entron** [comment]
That's correct.
