### ISSUE TITLE
Lagged features

### ISSUE THREAD

**Issue by hamelsmu** [entron/entity-embedding-rossmann#8]
Hi @entron I was wondering if you tried lagged variables?  Did they end up just not being that useful?

What was your experience trying to incorporate classic time series features into this dataset such as sales trends etc?  

Thanks for your insights.

**Comment by entron** [comment]
Hi @hamelsmu I have used some features which are probably what you mean by "lagged variables". They are statistics such as how many holidays in the past or upcomming week. Check the kaggle branch: https://github.com/entron/entity-embedding-rossmann/blob/kaggle/extract_fb_features.py

I haven't got time to try other time series features, but I remember the 2nd winner of this contest tried it. You can check his kaggle blog to see how he did.

**Comment by hamelsmu** [comment]
Hi Cheng what I mean by lagged variables is sales (lagged sum of target
variable) in last 7, 30, 60, 90 etc days to catch auto correlation?  Did
you try this?  I’m curious because it’s amazing that you did so well
without this, so I’m just making sure my understanding is correct.

**Comment by entron** [comment]
As far as I rember I didn't get time to try. I think these features would be very helpful.

**Comment by hamelsmu** [comment]
Thanks Cheng, appreciate the help!
