### ISSUE TITLE
Can't pickle <class 'module'>: attribute lookup module on builtins failed

### ISSUE THREAD

**Issue by r20041101** [entron/entity-embedding-rossmann#9]
Hi entron,

I got a problem when I pickle.dump the models.

Traceback (most recent call last):
  File "train_test_model.py", line 90, in <module>
    pickle.dump(models, f)
_pickle.PicklingError: Can't pickle <class 'module'>: attribute lookup module on builtins failed

Cloud you give me some ideas? very thanks.

**Comment by entron** [comment]
Which keras version are you using?

**Comment by r20041101** [comment]
1.2.2

**Comment by entron** [comment]
I haven't seen this problem before. Maybe you can use keras save instead of the pickle dump as suggested by: https://stackoverflow.com/questions/45289892/picklingerror-cant-pickle-class-module-attribute-lookup-module-on-builtin
